name: tufisioencasa
favicon: null
layout_spectrum: 0.74096
typography_spectrum: 0.8517170751001686
title: fisioterapia en casa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#97c00e'
    - '#5bc5ed'
    - '#e21770'
    - '#e85f54'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
